# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/arturamorim/Desktop/PomeronHVQCD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/arturamorim/Desktop/PomeronHVQCD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arturamorim/Desktop/PomeronHVQCD/CMakeFiles /Users/arturamorim/Desktop/PomeronHVQCD/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arturamorim/Desktop/PomeronHVQCD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_schrodinger.exe

# Build rule for target.
test_schrodinger.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_schrodinger.exe
.PHONY : test_schrodinger.exe

# fast build rule for target.
test_schrodinger.exe/fast:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/build
.PHONY : test_schrodinger.exe/fast

#=============================================================================
# Target rules for targets named HVQCDRatios.exe

# Build rule for target.
HVQCDRatios.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HVQCDRatios.exe
.PHONY : HVQCDRatios.exe

# fast build rule for target.
HVQCDRatios.exe/fast:
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/build
.PHONY : HVQCDRatios.exe/fast

#=============================================================================
# Target rules for targets named test_HVQCD.exe

# Build rule for target.
test_HVQCD.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_HVQCD.exe
.PHONY : test_HVQCD.exe

# fast build rule for target.
test_HVQCD.exe/fast:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/build
.PHONY : test_HVQCD.exe/fast

#=============================================================================
# Target rules for targets named fitSingletAVM.exe

# Build rule for target.
fitSingletAVM.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fitSingletAVM.exe
.PHONY : fitSingletAVM.exe

# fast build rule for target.
fitSingletAVM.exe/fast:
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/build
.PHONY : fitSingletAVM.exe/fast

#=============================================================================
# Target rules for targets named fitHVQCDGlobal_sc_VgIR_fixed.exe

# Build rule for target.
fitHVQCDGlobal_sc_VgIR_fixed.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fitHVQCDGlobal_sc_VgIR_fixed.exe
.PHONY : fitHVQCDGlobal_sc_VgIR_fixed.exe

# fast build rule for target.
fitHVQCDGlobal_sc_VgIR_fixed.exe/fast:
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build
.PHONY : fitHVQCDGlobal_sc_VgIR_fixed.exe/fast

#=============================================================================
# Target rules for targets named fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe

# Build rule for target.
fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe
.PHONY : fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe

# fast build rule for target.
fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe/fast:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build
.PHONY : fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe/fast

#=============================================================================
# Target rules for targets named fitHVQCDWithoutScalars_sc_VgIR_fixed.exe

# Build rule for target.
fitHVQCDWithoutScalars_sc_VgIR_fixed.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fitHVQCDWithoutScalars_sc_VgIR_fixed.exe
.PHONY : fitHVQCDWithoutScalars_sc_VgIR_fixed.exe

# fast build rule for target.
fitHVQCDWithoutScalars_sc_VgIR_fixed.exe/fast:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build
.PHONY : fitHVQCDWithoutScalars_sc_VgIR_fixed.exe/fast

#=============================================================================
# Target rules for targets named fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe

# Build rule for target.
fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe
.PHONY : fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe

# fast build rule for target.
fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe/fast:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build
.PHONY : fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe/fast

#=============================================================================
# Target rules for targets named fitHVQCDGlobal.exe

# Build rule for target.
fitHVQCDGlobal.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fitHVQCDGlobal.exe
.PHONY : fitHVQCDGlobal.exe

# fast build rule for target.
fitHVQCDGlobal.exe/fast:
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/build
.PHONY : fitHVQCDGlobal.exe/fast

#=============================================================================
# Target rules for targets named fitHVQCDWithoutScalars.exe

# Build rule for target.
fitHVQCDWithoutScalars.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fitHVQCDWithoutScalars.exe
.PHONY : fitHVQCDWithoutScalars.exe

# fast build rule for target.
fitHVQCDWithoutScalars.exe/fast:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build
.PHONY : fitHVQCDWithoutScalars.exe/fast

#=============================================================================
# Target rules for targets named fitYangMills.exe

# Build rule for target.
fitYangMills.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fitYangMills.exe
.PHONY : fitYangMills.exe

# fast build rule for target.
fitYangMills.exe/fast:
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/build
.PHONY : fitYangMills.exe/fast

physics/HVQCDRatios.o: physics/HVQCDRatios.cpp.o

.PHONY : physics/HVQCDRatios.o

# target to build an object file
physics/HVQCDRatios.cpp.o:
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/physics/HVQCDRatios.cpp.o
.PHONY : physics/HVQCDRatios.cpp.o

physics/HVQCDRatios.i: physics/HVQCDRatios.cpp.i

.PHONY : physics/HVQCDRatios.i

# target to preprocess a source file
physics/HVQCDRatios.cpp.i:
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/physics/HVQCDRatios.cpp.i
.PHONY : physics/HVQCDRatios.cpp.i

physics/HVQCDRatios.s: physics/HVQCDRatios.cpp.s

.PHONY : physics/HVQCDRatios.s

# target to generate assembly for a file
physics/HVQCDRatios.cpp.s:
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/physics/HVQCDRatios.cpp.s
.PHONY : physics/HVQCDRatios.cpp.s

physics/fitHVQCDGlobal.o: physics/fitHVQCDGlobal.cpp.o

.PHONY : physics/fitHVQCDGlobal.o

# target to build an object file
physics/fitHVQCDGlobal.cpp.o:
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/physics/fitHVQCDGlobal.cpp.o
.PHONY : physics/fitHVQCDGlobal.cpp.o

physics/fitHVQCDGlobal.i: physics/fitHVQCDGlobal.cpp.i

.PHONY : physics/fitHVQCDGlobal.i

# target to preprocess a source file
physics/fitHVQCDGlobal.cpp.i:
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/physics/fitHVQCDGlobal.cpp.i
.PHONY : physics/fitHVQCDGlobal.cpp.i

physics/fitHVQCDGlobal.s: physics/fitHVQCDGlobal.cpp.s

.PHONY : physics/fitHVQCDGlobal.s

# target to generate assembly for a file
physics/fitHVQCDGlobal.cpp.s:
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/physics/fitHVQCDGlobal.cpp.s
.PHONY : physics/fitHVQCDGlobal.cpp.s

physics/fitHVQCDGlobal_sc_VgIR_fixed.o: physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.o

.PHONY : physics/fitHVQCDGlobal_sc_VgIR_fixed.o

# target to build an object file
physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.o:
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.o
.PHONY : physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.o

physics/fitHVQCDGlobal_sc_VgIR_fixed.i: physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.i

.PHONY : physics/fitHVQCDGlobal_sc_VgIR_fixed.i

# target to preprocess a source file
physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.i:
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.i
.PHONY : physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.i

physics/fitHVQCDGlobal_sc_VgIR_fixed.s: physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.s

.PHONY : physics/fitHVQCDGlobal_sc_VgIR_fixed.s

# target to generate assembly for a file
physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.s:
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.s
.PHONY : physics/fitHVQCDGlobal_sc_VgIR_fixed.cpp.s

physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.o: physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.o

.PHONY : physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.o

# target to build an object file
physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.o:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.o
.PHONY : physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.o

physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.i: physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.i

.PHONY : physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.i

# target to preprocess a source file
physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.i:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.i
.PHONY : physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.i

physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.s: physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.s

.PHONY : physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.s

# target to generate assembly for a file
physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.s:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.s
.PHONY : physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.cpp.s

physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.o: physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.o

.PHONY : physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.o

# target to build an object file
physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.o:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.o
.PHONY : physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.o

physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.i: physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.i

.PHONY : physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.i

# target to preprocess a source file
physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.i:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.i
.PHONY : physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.i

physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.s: physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.s

.PHONY : physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.s

# target to generate assembly for a file
physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.s:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.s
.PHONY : physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.cpp.s

physics/fitHVQCDWithoutScalars.o: physics/fitHVQCDWithoutScalars.cpp.o

.PHONY : physics/fitHVQCDWithoutScalars.o

# target to build an object file
physics/fitHVQCDWithoutScalars.cpp.o:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/physics/fitHVQCDWithoutScalars.cpp.o
.PHONY : physics/fitHVQCDWithoutScalars.cpp.o

physics/fitHVQCDWithoutScalars.i: physics/fitHVQCDWithoutScalars.cpp.i

.PHONY : physics/fitHVQCDWithoutScalars.i

# target to preprocess a source file
physics/fitHVQCDWithoutScalars.cpp.i:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/physics/fitHVQCDWithoutScalars.cpp.i
.PHONY : physics/fitHVQCDWithoutScalars.cpp.i

physics/fitHVQCDWithoutScalars.s: physics/fitHVQCDWithoutScalars.cpp.s

.PHONY : physics/fitHVQCDWithoutScalars.s

# target to generate assembly for a file
physics/fitHVQCDWithoutScalars.cpp.s:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/physics/fitHVQCDWithoutScalars.cpp.s
.PHONY : physics/fitHVQCDWithoutScalars.cpp.s

physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.o: physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.o

.PHONY : physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.o

# target to build an object file
physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.o:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.o
.PHONY : physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.o

physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.i: physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.i

.PHONY : physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.i

# target to preprocess a source file
physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.i:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.i
.PHONY : physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.i

physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.s: physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.s

.PHONY : physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.s

# target to generate assembly for a file
physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.s:
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.s
.PHONY : physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.cpp.s

physics/fitSingletAVM.o: physics/fitSingletAVM.cpp.o

.PHONY : physics/fitSingletAVM.o

# target to build an object file
physics/fitSingletAVM.cpp.o:
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/physics/fitSingletAVM.cpp.o
.PHONY : physics/fitSingletAVM.cpp.o

physics/fitSingletAVM.i: physics/fitSingletAVM.cpp.i

.PHONY : physics/fitSingletAVM.i

# target to preprocess a source file
physics/fitSingletAVM.cpp.i:
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/physics/fitSingletAVM.cpp.i
.PHONY : physics/fitSingletAVM.cpp.i

physics/fitSingletAVM.s: physics/fitSingletAVM.cpp.s

.PHONY : physics/fitSingletAVM.s

# target to generate assembly for a file
physics/fitSingletAVM.cpp.s:
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/physics/fitSingletAVM.cpp.s
.PHONY : physics/fitSingletAVM.cpp.s

physics/fitYangMills.o: physics/fitYangMills.cpp.o

.PHONY : physics/fitYangMills.o

# target to build an object file
physics/fitYangMills.cpp.o:
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/physics/fitYangMills.cpp.o
.PHONY : physics/fitYangMills.cpp.o

physics/fitYangMills.i: physics/fitYangMills.cpp.i

.PHONY : physics/fitYangMills.i

# target to preprocess a source file
physics/fitYangMills.cpp.i:
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/physics/fitYangMills.cpp.i
.PHONY : physics/fitYangMills.cpp.i

physics/fitYangMills.s: physics/fitYangMills.cpp.s

.PHONY : physics/fitYangMills.s

# target to generate assembly for a file
physics/fitYangMills.cpp.s:
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/physics/fitYangMills.cpp.s
.PHONY : physics/fitYangMills.cpp.s

src/HolographicVQCD.o: src/HolographicVQCD.cpp.o

.PHONY : src/HolographicVQCD.o

# target to build an object file
src/HolographicVQCD.cpp.o:
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/HolographicVQCD.cpp.o
.PHONY : src/HolographicVQCD.cpp.o

src/HolographicVQCD.i: src/HolographicVQCD.cpp.i

.PHONY : src/HolographicVQCD.i

# target to preprocess a source file
src/HolographicVQCD.cpp.i:
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/HolographicVQCD.cpp.i
.PHONY : src/HolographicVQCD.cpp.i

src/HolographicVQCD.s: src/HolographicVQCD.cpp.s

.PHONY : src/HolographicVQCD.s

# target to generate assembly for a file
src/HolographicVQCD.cpp.s:
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/HolographicVQCD.cpp.s
.PHONY : src/HolographicVQCD.cpp.s

src/YangMills.o: src/YangMills.cpp.o

.PHONY : src/YangMills.o

# target to build an object file
src/YangMills.cpp.o:
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/YangMills.cpp.o
.PHONY : src/YangMills.cpp.o

src/YangMills.i: src/YangMills.cpp.i

.PHONY : src/YangMills.i

# target to preprocess a source file
src/YangMills.cpp.i:
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/YangMills.cpp.i
.PHONY : src/YangMills.cpp.i

src/YangMills.s: src/YangMills.cpp.s

.PHONY : src/YangMills.s

# target to generate assembly for a file
src/YangMills.cpp.s:
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/YangMills.cpp.s
.PHONY : src/YangMills.cpp.s

src/background.o: src/background.cpp.o

.PHONY : src/background.o

# target to build an object file
src/background.cpp.o:
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/background.cpp.o
.PHONY : src/background.cpp.o

src/background.i: src/background.cpp.i

.PHONY : src/background.i

# target to preprocess a source file
src/background.cpp.i:
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/background.cpp.i
.PHONY : src/background.cpp.i

src/background.s: src/background.cpp.s

.PHONY : src/background.s

# target to generate assembly for a file
src/background.cpp.s:
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/background.cpp.s
.PHONY : src/background.cpp.s

src/schrodinger/chebspec.o: src/schrodinger/chebspec.cpp.o

.PHONY : src/schrodinger/chebspec.o

# target to build an object file
src/schrodinger/chebspec.cpp.o:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/chebspec.cpp.o
.PHONY : src/schrodinger/chebspec.cpp.o

src/schrodinger/chebspec.i: src/schrodinger/chebspec.cpp.i

.PHONY : src/schrodinger/chebspec.i

# target to preprocess a source file
src/schrodinger/chebspec.cpp.i:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/chebspec.cpp.i
.PHONY : src/schrodinger/chebspec.cpp.i

src/schrodinger/chebspec.s: src/schrodinger/chebspec.cpp.s

.PHONY : src/schrodinger/chebspec.s

# target to generate assembly for a file
src/schrodinger/chebspec.cpp.s:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/chebspec.cpp.s
.PHONY : src/schrodinger/chebspec.cpp.s

src/schrodinger/common.o: src/schrodinger/common.cpp.o

.PHONY : src/schrodinger/common.o

# target to build an object file
src/schrodinger/common.cpp.o:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/common.cpp.o
.PHONY : src/schrodinger/common.cpp.o

src/schrodinger/common.i: src/schrodinger/common.cpp.i

.PHONY : src/schrodinger/common.i

# target to preprocess a source file
src/schrodinger/common.cpp.i:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/common.cpp.i
.PHONY : src/schrodinger/common.cpp.i

src/schrodinger/common.s: src/schrodinger/common.cpp.s

.PHONY : src/schrodinger/common.s

# target to generate assembly for a file
src/schrodinger/common.cpp.s:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/common.cpp.s
.PHONY : src/schrodinger/common.cpp.s

src/schrodinger/numerov.o: src/schrodinger/numerov.cpp.o

.PHONY : src/schrodinger/numerov.o

# target to build an object file
src/schrodinger/numerov.cpp.o:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/numerov.cpp.o
.PHONY : src/schrodinger/numerov.cpp.o

src/schrodinger/numerov.i: src/schrodinger/numerov.cpp.i

.PHONY : src/schrodinger/numerov.i

# target to preprocess a source file
src/schrodinger/numerov.cpp.i:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/numerov.cpp.i
.PHONY : src/schrodinger/numerov.cpp.i

src/schrodinger/numerov.s: src/schrodinger/numerov.cpp.s

.PHONY : src/schrodinger/numerov.s

# target to generate assembly for a file
src/schrodinger/numerov.cpp.s:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/numerov.cpp.s
.PHONY : src/schrodinger/numerov.cpp.s

src/schrodinger/schrodinger.o: src/schrodinger/schrodinger.cpp.o

.PHONY : src/schrodinger/schrodinger.o

# target to build an object file
src/schrodinger/schrodinger.cpp.o:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/schrodinger.cpp.o
.PHONY : src/schrodinger/schrodinger.cpp.o

src/schrodinger/schrodinger.i: src/schrodinger/schrodinger.cpp.i

.PHONY : src/schrodinger/schrodinger.i

# target to preprocess a source file
src/schrodinger/schrodinger.cpp.i:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/schrodinger.cpp.i
.PHONY : src/schrodinger/schrodinger.cpp.i

src/schrodinger/schrodinger.s: src/schrodinger/schrodinger.cpp.s

.PHONY : src/schrodinger/schrodinger.s

# target to generate assembly for a file
src/schrodinger/schrodinger.cpp.s:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/schrodinger.cpp.s
.PHONY : src/schrodinger/schrodinger.cpp.s

src/schrodinger/solvspec.o: src/schrodinger/solvspec.cpp.o

.PHONY : src/schrodinger/solvspec.o

# target to build an object file
src/schrodinger/solvspec.cpp.o:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/solvspec.cpp.o
.PHONY : src/schrodinger/solvspec.cpp.o

src/schrodinger/solvspec.i: src/schrodinger/solvspec.cpp.i

.PHONY : src/schrodinger/solvspec.i

# target to preprocess a source file
src/schrodinger/solvspec.cpp.i:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/solvspec.cpp.i
.PHONY : src/schrodinger/solvspec.cpp.i

src/schrodinger/solvspec.s: src/schrodinger/solvspec.cpp.s

.PHONY : src/schrodinger/solvspec.s

# target to generate assembly for a file
src/schrodinger/solvspec.cpp.s:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/HVQCDRatios.exe.dir/build.make CMakeFiles/HVQCDRatios.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAVM.exe.dir/build.make CMakeFiles/fitSingletAVM.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDGlobal_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/build.make CMakeFiles/fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDGlobal.exe.dir/build.make CMakeFiles/fitHVQCDGlobal.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/fitHVQCDWithoutScalars.exe.dir/build.make CMakeFiles/fitHVQCDWithoutScalars.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/fitYangMills.exe.dir/build.make CMakeFiles/fitYangMills.exe.dir/src/schrodinger/solvspec.cpp.s
.PHONY : src/schrodinger/solvspec.cpp.s

tests/test_HVQCD.o: tests/test_HVQCD.cpp.o

.PHONY : tests/test_HVQCD.o

# target to build an object file
tests/test_HVQCD.cpp.o:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/tests/test_HVQCD.cpp.o
.PHONY : tests/test_HVQCD.cpp.o

tests/test_HVQCD.i: tests/test_HVQCD.cpp.i

.PHONY : tests/test_HVQCD.i

# target to preprocess a source file
tests/test_HVQCD.cpp.i:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/tests/test_HVQCD.cpp.i
.PHONY : tests/test_HVQCD.cpp.i

tests/test_HVQCD.s: tests/test_HVQCD.cpp.s

.PHONY : tests/test_HVQCD.s

# target to generate assembly for a file
tests/test_HVQCD.cpp.s:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/tests/test_HVQCD.cpp.s
.PHONY : tests/test_HVQCD.cpp.s

tests/test_schrodinger.o: tests/test_schrodinger.cpp.o

.PHONY : tests/test_schrodinger.o

# target to build an object file
tests/test_schrodinger.cpp.o:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/tests/test_schrodinger.cpp.o
.PHONY : tests/test_schrodinger.cpp.o

tests/test_schrodinger.i: tests/test_schrodinger.cpp.i

.PHONY : tests/test_schrodinger.i

# target to preprocess a source file
tests/test_schrodinger.cpp.i:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/tests/test_schrodinger.cpp.i
.PHONY : tests/test_schrodinger.cpp.i

tests/test_schrodinger.s: tests/test_schrodinger.cpp.s

.PHONY : tests/test_schrodinger.s

# target to generate assembly for a file
tests/test_schrodinger.cpp.s:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/tests/test_schrodinger.cpp.s
.PHONY : tests/test_schrodinger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_schrodinger.exe"
	@echo "... HVQCDRatios.exe"
	@echo "... test_HVQCD.exe"
	@echo "... fitSingletAVM.exe"
	@echo "... fitHVQCDGlobal_sc_VgIR_fixed.exe"
	@echo "... fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.exe"
	@echo "... fitHVQCDWithoutScalars_sc_VgIR_fixed.exe"
	@echo "... fitHVQCDWithoutGlueball_sc_VgIR_fixed.exe"
	@echo "... fitHVQCDGlobal.exe"
	@echo "... fitHVQCDWithoutScalars.exe"
	@echo "... fitYangMills.exe"
	@echo "... physics/HVQCDRatios.o"
	@echo "... physics/HVQCDRatios.i"
	@echo "... physics/HVQCDRatios.s"
	@echo "... physics/fitHVQCDGlobal.o"
	@echo "... physics/fitHVQCDGlobal.i"
	@echo "... physics/fitHVQCDGlobal.s"
	@echo "... physics/fitHVQCDGlobal_sc_VgIR_fixed.o"
	@echo "... physics/fitHVQCDGlobal_sc_VgIR_fixed.i"
	@echo "... physics/fitHVQCDGlobal_sc_VgIR_fixed.s"
	@echo "... physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.o"
	@echo "... physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.i"
	@echo "... physics/fitHVQCDWithoutGlueballScalars_sc_VgIR_fixed.s"
	@echo "... physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.o"
	@echo "... physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.i"
	@echo "... physics/fitHVQCDWithoutGlueball_sc_VgIR_fixed.s"
	@echo "... physics/fitHVQCDWithoutScalars.o"
	@echo "... physics/fitHVQCDWithoutScalars.i"
	@echo "... physics/fitHVQCDWithoutScalars.s"
	@echo "... physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.o"
	@echo "... physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.i"
	@echo "... physics/fitHVQCDWithoutScalars_sc_VgIR_fixed.s"
	@echo "... physics/fitSingletAVM.o"
	@echo "... physics/fitSingletAVM.i"
	@echo "... physics/fitSingletAVM.s"
	@echo "... physics/fitYangMills.o"
	@echo "... physics/fitYangMills.i"
	@echo "... physics/fitYangMills.s"
	@echo "... src/HolographicVQCD.o"
	@echo "... src/HolographicVQCD.i"
	@echo "... src/HolographicVQCD.s"
	@echo "... src/YangMills.o"
	@echo "... src/YangMills.i"
	@echo "... src/YangMills.s"
	@echo "... src/background.o"
	@echo "... src/background.i"
	@echo "... src/background.s"
	@echo "... src/schrodinger/chebspec.o"
	@echo "... src/schrodinger/chebspec.i"
	@echo "... src/schrodinger/chebspec.s"
	@echo "... src/schrodinger/common.o"
	@echo "... src/schrodinger/common.i"
	@echo "... src/schrodinger/common.s"
	@echo "... src/schrodinger/numerov.o"
	@echo "... src/schrodinger/numerov.i"
	@echo "... src/schrodinger/numerov.s"
	@echo "... src/schrodinger/schrodinger.o"
	@echo "... src/schrodinger/schrodinger.i"
	@echo "... src/schrodinger/schrodinger.s"
	@echo "... src/schrodinger/solvspec.o"
	@echo "... src/schrodinger/solvspec.i"
	@echo "... src/schrodinger/solvspec.s"
	@echo "... tests/test_HVQCD.o"
	@echo "... tests/test_HVQCD.i"
	@echo "... tests/test_HVQCD.s"
	@echo "... tests/test_schrodinger.o"
	@echo "... tests/test_schrodinger.i"
	@echo "... tests/test_schrodinger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

