# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/arturamorim/Desktop/PomeronHVQCD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/arturamorim/Desktop/PomeronHVQCD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arturamorim/Desktop/PomeronHVQCD/CMakeFiles /Users/arturamorim/Desktop/PomeronHVQCD/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arturamorim/Desktop/PomeronHVQCD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_HVQCD.exe

# Build rule for target.
test_HVQCD.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_HVQCD.exe
.PHONY : test_HVQCD.exe

# fast build rule for target.
test_HVQCD.exe/fast:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/build
.PHONY : test_HVQCD.exe/fast

#=============================================================================
# Target rules for targets named test_schrodinger.exe

# Build rule for target.
test_schrodinger.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_schrodinger.exe
.PHONY : test_schrodinger.exe

# fast build rule for target.
test_schrodinger.exe/fast:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/build
.PHONY : test_schrodinger.exe/fast

#=============================================================================
# Target rules for targets named HVQCD_mass_ratios.exe

# Build rule for target.
HVQCD_mass_ratios.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HVQCD_mass_ratios.exe
.PHONY : HVQCD_mass_ratios.exe

# fast build rule for target.
HVQCD_mass_ratios.exe/fast:
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/build
.PHONY : HVQCD_mass_ratios.exe/fast

#=============================================================================
# Target rules for targets named fittingBackground.exe

# Build rule for target.
fittingBackground.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fittingBackground.exe
.PHONY : fittingBackground.exe

# fast build rule for target.
fittingBackground.exe/fast:
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/build
.PHONY : fittingBackground.exe/fast

#=============================================================================
# Target rules for targets named fitSingletAxialVectorMesons.exe

# Build rule for target.
fitSingletAxialVectorMesons.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fitSingletAxialVectorMesons.exe
.PHONY : fitSingletAxialVectorMesons.exe

# fast build rule for target.
fitSingletAxialVectorMesons.exe/fast:
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build
.PHONY : fitSingletAxialVectorMesons.exe/fast

#=============================================================================
# Target rules for targets named fitBackground_kU1_not_fixed.exe

# Build rule for target.
fitBackground_kU1_not_fixed.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fitBackground_kU1_not_fixed.exe
.PHONY : fitBackground_kU1_not_fixed.exe

# fast build rule for target.
fitBackground_kU1_not_fixed.exe/fast:
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build
.PHONY : fitBackground_kU1_not_fixed.exe/fast

physics/HVQCD_mass_ratios.o: physics/HVQCD_mass_ratios.cpp.o

.PHONY : physics/HVQCD_mass_ratios.o

# target to build an object file
physics/HVQCD_mass_ratios.cpp.o:
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/physics/HVQCD_mass_ratios.cpp.o
.PHONY : physics/HVQCD_mass_ratios.cpp.o

physics/HVQCD_mass_ratios.i: physics/HVQCD_mass_ratios.cpp.i

.PHONY : physics/HVQCD_mass_ratios.i

# target to preprocess a source file
physics/HVQCD_mass_ratios.cpp.i:
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/physics/HVQCD_mass_ratios.cpp.i
.PHONY : physics/HVQCD_mass_ratios.cpp.i

physics/HVQCD_mass_ratios.s: physics/HVQCD_mass_ratios.cpp.s

.PHONY : physics/HVQCD_mass_ratios.s

# target to generate assembly for a file
physics/HVQCD_mass_ratios.cpp.s:
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/physics/HVQCD_mass_ratios.cpp.s
.PHONY : physics/HVQCD_mass_ratios.cpp.s

physics/fitBackground_kU1_not_fixed.o: physics/fitBackground_kU1_not_fixed.cpp.o

.PHONY : physics/fitBackground_kU1_not_fixed.o

# target to build an object file
physics/fitBackground_kU1_not_fixed.cpp.o:
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/physics/fitBackground_kU1_not_fixed.cpp.o
.PHONY : physics/fitBackground_kU1_not_fixed.cpp.o

physics/fitBackground_kU1_not_fixed.i: physics/fitBackground_kU1_not_fixed.cpp.i

.PHONY : physics/fitBackground_kU1_not_fixed.i

# target to preprocess a source file
physics/fitBackground_kU1_not_fixed.cpp.i:
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/physics/fitBackground_kU1_not_fixed.cpp.i
.PHONY : physics/fitBackground_kU1_not_fixed.cpp.i

physics/fitBackground_kU1_not_fixed.s: physics/fitBackground_kU1_not_fixed.cpp.s

.PHONY : physics/fitBackground_kU1_not_fixed.s

# target to generate assembly for a file
physics/fitBackground_kU1_not_fixed.cpp.s:
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/physics/fitBackground_kU1_not_fixed.cpp.s
.PHONY : physics/fitBackground_kU1_not_fixed.cpp.s

physics/fitSingletAxialVectorMesons.o: physics/fitSingletAxialVectorMesons.cpp.o

.PHONY : physics/fitSingletAxialVectorMesons.o

# target to build an object file
physics/fitSingletAxialVectorMesons.cpp.o:
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/physics/fitSingletAxialVectorMesons.cpp.o
.PHONY : physics/fitSingletAxialVectorMesons.cpp.o

physics/fitSingletAxialVectorMesons.i: physics/fitSingletAxialVectorMesons.cpp.i

.PHONY : physics/fitSingletAxialVectorMesons.i

# target to preprocess a source file
physics/fitSingletAxialVectorMesons.cpp.i:
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/physics/fitSingletAxialVectorMesons.cpp.i
.PHONY : physics/fitSingletAxialVectorMesons.cpp.i

physics/fitSingletAxialVectorMesons.s: physics/fitSingletAxialVectorMesons.cpp.s

.PHONY : physics/fitSingletAxialVectorMesons.s

# target to generate assembly for a file
physics/fitSingletAxialVectorMesons.cpp.s:
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/physics/fitSingletAxialVectorMesons.cpp.s
.PHONY : physics/fitSingletAxialVectorMesons.cpp.s

physics/fittingBackground.o: physics/fittingBackground.cpp.o

.PHONY : physics/fittingBackground.o

# target to build an object file
physics/fittingBackground.cpp.o:
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/physics/fittingBackground.cpp.o
.PHONY : physics/fittingBackground.cpp.o

physics/fittingBackground.i: physics/fittingBackground.cpp.i

.PHONY : physics/fittingBackground.i

# target to preprocess a source file
physics/fittingBackground.cpp.i:
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/physics/fittingBackground.cpp.i
.PHONY : physics/fittingBackground.cpp.i

physics/fittingBackground.s: physics/fittingBackground.cpp.s

.PHONY : physics/fittingBackground.s

# target to generate assembly for a file
physics/fittingBackground.cpp.s:
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/physics/fittingBackground.cpp.s
.PHONY : physics/fittingBackground.cpp.s

src/HolographicVQCD.o: src/HolographicVQCD.cpp.o

.PHONY : src/HolographicVQCD.o

# target to build an object file
src/HolographicVQCD.cpp.o:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/HolographicVQCD.cpp.o
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/HolographicVQCD.cpp.o
.PHONY : src/HolographicVQCD.cpp.o

src/HolographicVQCD.i: src/HolographicVQCD.cpp.i

.PHONY : src/HolographicVQCD.i

# target to preprocess a source file
src/HolographicVQCD.cpp.i:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/HolographicVQCD.cpp.i
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/HolographicVQCD.cpp.i
.PHONY : src/HolographicVQCD.cpp.i

src/HolographicVQCD.s: src/HolographicVQCD.cpp.s

.PHONY : src/HolographicVQCD.s

# target to generate assembly for a file
src/HolographicVQCD.cpp.s:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/HolographicVQCD.cpp.s
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/HolographicVQCD.cpp.s
.PHONY : src/HolographicVQCD.cpp.s

src/background.o: src/background.cpp.o

.PHONY : src/background.o

# target to build an object file
src/background.cpp.o:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/background.cpp.o
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/background.cpp.o
.PHONY : src/background.cpp.o

src/background.i: src/background.cpp.i

.PHONY : src/background.i

# target to preprocess a source file
src/background.cpp.i:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/background.cpp.i
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/background.cpp.i
.PHONY : src/background.cpp.i

src/background.s: src/background.cpp.s

.PHONY : src/background.s

# target to generate assembly for a file
src/background.cpp.s:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/background.cpp.s
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/background.cpp.s
.PHONY : src/background.cpp.s

src/schrodinger/chebspec.o: src/schrodinger/chebspec.cpp.o

.PHONY : src/schrodinger/chebspec.o

# target to build an object file
src/schrodinger/chebspec.cpp.o:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/chebspec.cpp.o
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/chebspec.cpp.o
.PHONY : src/schrodinger/chebspec.cpp.o

src/schrodinger/chebspec.i: src/schrodinger/chebspec.cpp.i

.PHONY : src/schrodinger/chebspec.i

# target to preprocess a source file
src/schrodinger/chebspec.cpp.i:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/chebspec.cpp.i
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/chebspec.cpp.i
.PHONY : src/schrodinger/chebspec.cpp.i

src/schrodinger/chebspec.s: src/schrodinger/chebspec.cpp.s

.PHONY : src/schrodinger/chebspec.s

# target to generate assembly for a file
src/schrodinger/chebspec.cpp.s:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/chebspec.cpp.s
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/chebspec.cpp.s
.PHONY : src/schrodinger/chebspec.cpp.s

src/schrodinger/common.o: src/schrodinger/common.cpp.o

.PHONY : src/schrodinger/common.o

# target to build an object file
src/schrodinger/common.cpp.o:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/common.cpp.o
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/common.cpp.o
.PHONY : src/schrodinger/common.cpp.o

src/schrodinger/common.i: src/schrodinger/common.cpp.i

.PHONY : src/schrodinger/common.i

# target to preprocess a source file
src/schrodinger/common.cpp.i:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/common.cpp.i
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/common.cpp.i
.PHONY : src/schrodinger/common.cpp.i

src/schrodinger/common.s: src/schrodinger/common.cpp.s

.PHONY : src/schrodinger/common.s

# target to generate assembly for a file
src/schrodinger/common.cpp.s:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/common.cpp.s
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/common.cpp.s
.PHONY : src/schrodinger/common.cpp.s

src/schrodinger/numerov.o: src/schrodinger/numerov.cpp.o

.PHONY : src/schrodinger/numerov.o

# target to build an object file
src/schrodinger/numerov.cpp.o:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/numerov.cpp.o
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/numerov.cpp.o
.PHONY : src/schrodinger/numerov.cpp.o

src/schrodinger/numerov.i: src/schrodinger/numerov.cpp.i

.PHONY : src/schrodinger/numerov.i

# target to preprocess a source file
src/schrodinger/numerov.cpp.i:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/numerov.cpp.i
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/numerov.cpp.i
.PHONY : src/schrodinger/numerov.cpp.i

src/schrodinger/numerov.s: src/schrodinger/numerov.cpp.s

.PHONY : src/schrodinger/numerov.s

# target to generate assembly for a file
src/schrodinger/numerov.cpp.s:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/numerov.cpp.s
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/numerov.cpp.s
.PHONY : src/schrodinger/numerov.cpp.s

src/schrodinger/schrodinger.o: src/schrodinger/schrodinger.cpp.o

.PHONY : src/schrodinger/schrodinger.o

# target to build an object file
src/schrodinger/schrodinger.cpp.o:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/schrodinger.cpp.o
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/schrodinger.cpp.o
.PHONY : src/schrodinger/schrodinger.cpp.o

src/schrodinger/schrodinger.i: src/schrodinger/schrodinger.cpp.i

.PHONY : src/schrodinger/schrodinger.i

# target to preprocess a source file
src/schrodinger/schrodinger.cpp.i:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/schrodinger.cpp.i
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/schrodinger.cpp.i
.PHONY : src/schrodinger/schrodinger.cpp.i

src/schrodinger/schrodinger.s: src/schrodinger/schrodinger.cpp.s

.PHONY : src/schrodinger/schrodinger.s

# target to generate assembly for a file
src/schrodinger/schrodinger.cpp.s:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/schrodinger.cpp.s
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/schrodinger.cpp.s
.PHONY : src/schrodinger/schrodinger.cpp.s

src/schrodinger/solvspec.o: src/schrodinger/solvspec.cpp.o

.PHONY : src/schrodinger/solvspec.o

# target to build an object file
src/schrodinger/solvspec.cpp.o:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/solvspec.cpp.o
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/solvspec.cpp.o
.PHONY : src/schrodinger/solvspec.cpp.o

src/schrodinger/solvspec.i: src/schrodinger/solvspec.cpp.i

.PHONY : src/schrodinger/solvspec.i

# target to preprocess a source file
src/schrodinger/solvspec.cpp.i:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/solvspec.cpp.i
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/solvspec.cpp.i
.PHONY : src/schrodinger/solvspec.cpp.i

src/schrodinger/solvspec.s: src/schrodinger/solvspec.cpp.s

.PHONY : src/schrodinger/solvspec.s

# target to generate assembly for a file
src/schrodinger/solvspec.cpp.s:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/HVQCD_mass_ratios.exe.dir/build.make CMakeFiles/HVQCD_mass_ratios.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/fittingBackground.exe.dir/build.make CMakeFiles/fittingBackground.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/fitSingletAxialVectorMesons.exe.dir/build.make CMakeFiles/fitSingletAxialVectorMesons.exe.dir/src/schrodinger/solvspec.cpp.s
	$(MAKE) -f CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/build.make CMakeFiles/fitBackground_kU1_not_fixed.exe.dir/src/schrodinger/solvspec.cpp.s
.PHONY : src/schrodinger/solvspec.cpp.s

tests/test_HVQCD.o: tests/test_HVQCD.cpp.o

.PHONY : tests/test_HVQCD.o

# target to build an object file
tests/test_HVQCD.cpp.o:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/tests/test_HVQCD.cpp.o
.PHONY : tests/test_HVQCD.cpp.o

tests/test_HVQCD.i: tests/test_HVQCD.cpp.i

.PHONY : tests/test_HVQCD.i

# target to preprocess a source file
tests/test_HVQCD.cpp.i:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/tests/test_HVQCD.cpp.i
.PHONY : tests/test_HVQCD.cpp.i

tests/test_HVQCD.s: tests/test_HVQCD.cpp.s

.PHONY : tests/test_HVQCD.s

# target to generate assembly for a file
tests/test_HVQCD.cpp.s:
	$(MAKE) -f CMakeFiles/test_HVQCD.exe.dir/build.make CMakeFiles/test_HVQCD.exe.dir/tests/test_HVQCD.cpp.s
.PHONY : tests/test_HVQCD.cpp.s

tests/test_schrodinger.o: tests/test_schrodinger.cpp.o

.PHONY : tests/test_schrodinger.o

# target to build an object file
tests/test_schrodinger.cpp.o:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/tests/test_schrodinger.cpp.o
.PHONY : tests/test_schrodinger.cpp.o

tests/test_schrodinger.i: tests/test_schrodinger.cpp.i

.PHONY : tests/test_schrodinger.i

# target to preprocess a source file
tests/test_schrodinger.cpp.i:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/tests/test_schrodinger.cpp.i
.PHONY : tests/test_schrodinger.cpp.i

tests/test_schrodinger.s: tests/test_schrodinger.cpp.s

.PHONY : tests/test_schrodinger.s

# target to generate assembly for a file
tests/test_schrodinger.cpp.s:
	$(MAKE) -f CMakeFiles/test_schrodinger.exe.dir/build.make CMakeFiles/test_schrodinger.exe.dir/tests/test_schrodinger.cpp.s
.PHONY : tests/test_schrodinger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test_HVQCD.exe"
	@echo "... test_schrodinger.exe"
	@echo "... edit_cache"
	@echo "... HVQCD_mass_ratios.exe"
	@echo "... fittingBackground.exe"
	@echo "... rebuild_cache"
	@echo "... fitSingletAxialVectorMesons.exe"
	@echo "... fitBackground_kU1_not_fixed.exe"
	@echo "... physics/HVQCD_mass_ratios.o"
	@echo "... physics/HVQCD_mass_ratios.i"
	@echo "... physics/HVQCD_mass_ratios.s"
	@echo "... physics/fitBackground_kU1_not_fixed.o"
	@echo "... physics/fitBackground_kU1_not_fixed.i"
	@echo "... physics/fitBackground_kU1_not_fixed.s"
	@echo "... physics/fitSingletAxialVectorMesons.o"
	@echo "... physics/fitSingletAxialVectorMesons.i"
	@echo "... physics/fitSingletAxialVectorMesons.s"
	@echo "... physics/fittingBackground.o"
	@echo "... physics/fittingBackground.i"
	@echo "... physics/fittingBackground.s"
	@echo "... src/HolographicVQCD.o"
	@echo "... src/HolographicVQCD.i"
	@echo "... src/HolographicVQCD.s"
	@echo "... src/background.o"
	@echo "... src/background.i"
	@echo "... src/background.s"
	@echo "... src/schrodinger/chebspec.o"
	@echo "... src/schrodinger/chebspec.i"
	@echo "... src/schrodinger/chebspec.s"
	@echo "... src/schrodinger/common.o"
	@echo "... src/schrodinger/common.i"
	@echo "... src/schrodinger/common.s"
	@echo "... src/schrodinger/numerov.o"
	@echo "... src/schrodinger/numerov.i"
	@echo "... src/schrodinger/numerov.s"
	@echo "... src/schrodinger/schrodinger.o"
	@echo "... src/schrodinger/schrodinger.i"
	@echo "... src/schrodinger/schrodinger.s"
	@echo "... src/schrodinger/solvspec.o"
	@echo "... src/schrodinger/solvspec.i"
	@echo "... src/schrodinger/solvspec.s"
	@echo "... tests/test_HVQCD.o"
	@echo "... tests/test_HVQCD.i"
	@echo "... tests/test_HVQCD.s"
	@echo "... tests/test_schrodinger.o"
	@echo "... tests/test_schrodinger.i"
	@echo "... tests/test_schrodinger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

